CREATE TABLE [adi].[AETMA_Financial_MbrDetails] (
    [AETMA_Financial_MbrDetailsKey]    INT           IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]                 VARCHAR (100) NOT NULL,
    [SrcFileName]                      VARCHAR (100) NOT NULL,
    [LoadDate]                         DATE          NOT NULL,
    [CreatedDate]                      DATE          CONSTRAINT [DF_AETMA_Financial_MbrDetailsCreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                        VARCHAR (50)  CONSTRAINT [DF_AETMA_Financial_MbrDetailsCreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]                  DATETIME      CONSTRAINT [DF_AETMA_Financial_MbrDetails_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                    VARCHAR (50)  CONSTRAINT [DF_AETMA_Financial_MbrDetails_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ReportGroup]                      VARCHAR (50)  NULL,
    [ReportGroupName]                  VARCHAR (50)  NULL,
    [SubgroupNumber]                   VARCHAR (50)  NULL,
    [SubgroupName]                     VARCHAR (50)  NULL,
    [TIN]                              VARCHAR (12)  NULL,
    [TINName]                          VARCHAR (50)  NULL,
    [PVN]                              VARCHAR (50)  NULL,
    [PIN]                              VARCHAR (50)  NULL,
    [ProviderName]                     VARCHAR (50)  NULL,
    [EffectiveMonth]                   VARCHAR (50)  NULL,
    [Legacy]                           VARCHAR (50)  NULL,
    [SRCMemberID]                      VARCHAR (50)  NULL,
    [LastName]                         VARCHAR (50)  NULL,
    [FirstName]                        VARCHAR (50)  NULL,
    [Age]                              VARCHAR (10)  NULL,
    [AgeBand]                          VARCHAR (50)  NULL,
    [Gender]                           VARCHAR (10)  NULL,
    [Product]                          VARCHAR (50)  NULL,
    [CMSContract]                      VARCHAR (50)  NULL,
    [PBPID]                            VARCHAR (50)  NULL,
    [LineBusiness]                     VARCHAR (50)  NULL,
    [RiskScore_Projected]              VARCHAR (50)  NULL,
    [Revenue]                          VARCHAR (50)  NULL,
    [MedicalRxCost]                    VARCHAR (50)  NULL,
    [MedicalCostFundPer]               VARCHAR (50)  NULL,
    [RevenueNoPartD]                   VARCHAR (50)  NULL,
    [MedicalRxCostNoPartD]             VARCHAR (50)  NULL,
    [EffectiveYear]                    VARCHAR (10)  NULL,
    [EffectiveMonthName]               VARCHAR (10)  NULL,
    [EffectiveDate]                    DATE          NULL,
    [TINReportName]                    VARCHAR (50)  NULL,
    [ProviderReportName]               VARCHAR (50)  NULL,
    [MemberMonths]                     VARCHAR (10)  NULL,
    [AsofDate]                         DATE          NULL,
    [Target]                           VARCHAR (50)  NULL,
    [LocalMarketName]                  VARCHAR (50)  NULL,
    [MarketAvgRiskScore_Projected]     VARCHAR (50)  NULL,
    [MarketMedicalRxCost_PMPM]         VARCHAR (50)  NULL,
    [MarketMedicalCostFund]            VARCHAR (50)  NULL,
    [MarketMedical_RxCostNoPartD_PMPM] VARCHAR (50)  NULL,
    [MarketRevenueNo_PartD_PMPM]       VARCHAR (50)  NULL,
    [MarketMedicalCostFund_NoPartD]    VARCHAR (50)  NULL,
    [MarketRevenue_PMPM]               VARCHAR (50)  NULL,
    [ProviderFirstName]                VARCHAR (50)  NULL,
    [ProviderMiddleName]               VARCHAR (50)  NULL,
    [ProviderLastName]                 VARCHAR (50)  NULL,
    [NPI]                              VARCHAR (20)  NULL,
    [Chapter]                          VARCHAR (20)  NULL,
    PRIMARY KEY CLUSTERED ([AETMA_Financial_MbrDetailsKey] ASC)
);

