CREATE TABLE [adi].[AETMA_IPUTILIZATION] (
    [AETMA_IPUTILIZATIONKey]       INT           IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]             VARCHAR (100) NOT NULL,
    [SrcFileName]                  VARCHAR (100) NOT NULL,
    [LoadDate]                     DATE          NOT NULL,
    [CreatedDate]                  DATE          CONSTRAINT [DF_AETMA_IPUTILIZATIONCreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                    VARCHAR (50)  CONSTRAINT [DF_AETMA_IPUTILIZATIONCreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]              DATETIME      CONSTRAINT [DF_AETMA_IPUTILIZATION_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                VARCHAR (50)  CONSTRAINT [DF_AETMA_IPUTILIZATION_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ProviderGroupNumber]          VARCHAR (50)  NULL,
    [ProviderGroupName]            VARCHAR (50)  NULL,
    [SubgroupName]                 VARCHAR (50)  NULL,
    [TIN]                          VARCHAR (20)  NULL,
    [TINName]                      VARCHAR (50)  NULL,
    [PIN]                          VARCHAR (20)  NULL,
    [ProviderName]                 VARCHAR (50)  NULL,
    [GroupIndicator]               VARCHAR (10)  NULL,
    [LocalMarketCode]              VARCHAR (20)  NULL,
    [LocalMarket]                  VARCHAR (50)  NULL,
    [Legacy]                       VARCHAR (20)  NULL,
    [BaselineInd]                  VARCHAR (20)  NULL,
    [MemberID]                     VARCHAR (20)  NULL,
    [Member]                       VARCHAR (50)  NULL,
    [YearMonth]                    VARCHAR (20)  NULL,
    [StartDate]                    DATE          NULL,
    [EndDate]                      DATE          NULL,
    [Admits]                       VARCHAR (20)  NULL,
    [Days]                         VARCHAR (10)  NULL,
    [Year]                         VARCHAR (10)  NULL,
    [Month]                        VARCHAR (20)  NULL,
    [Diagnosis]                    VARCHAR (50)  NULL,
    [MedicalCaseID]                VARCHAR (20)  NULL,
    [ServiceProviderID]            VARCHAR (20)  NULL,
    [ServiceProviderName]          VARCHAR (50)  NULL,
    [ProviderType]                 VARCHAR (50)  NULL,
    [InpatientType]                VARCHAR (20)  NULL,
    [Day_14_Follow_up_OfficeVisit] VARCHAR (10)  NULL,
    [Data_AS_OF]                   DATE          NULL,
    PRIMARY KEY CLUSTERED ([AETMA_IPUTILIZATIONKey] ASC)
);

