CREATE TABLE [adi].[AETMA_MedAdherencePlans] (
    [AETMAMedAdherencePlansKey]       INT             IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                     VARCHAR (100)   NULL,
    [FileDate]                        DATE            NULL,
    [CreateDate]                      DATETIME        DEFAULT (sysdatetime()) NULL,
    [CreateBy]                        VARCHAR (100)   DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                VARCHAR (100)   NULL,
    [LastUpdatedBy]                   VARCHAR (100)   NULL,
    [LastUpdatedDate]                 DATETIME        NULL,
    [DataDate]                        DATE            NULL,
    [ProviderGroupNumber]             VARCHAR (50)    NULL,
    [ProviderGroupName]               VARCHAR (50)    NULL,
    [TIN]                             VARCHAR (9)     NULL,
    [TINName]                         VARCHAR (50)    NULL,
    [PIN]                             VARCHAR (20)    NULL,
    [NPI]                             VARCHAR (10)    NULL,
    [ProviderName]                    VARCHAR (50)    NULL,
    [MemberID]                        VARCHAR (20)    NULL,
    [CVTYMemberID]                    VARCHAR (50)    NULL,
    [MemberFirstName]                 VARCHAR (50)    NULL,
    [MemberLastName]                  VARCHAR (50)    NULL,
    [MemberDateofBirth]               DATE            NULL,
    [MemberPhoneNumber]               VARCHAR (50)    NULL,
    [MemberAddressLine1]              VARCHAR (50)    NULL,
    [MemberCity]                      VARCHAR (50)    NULL,
    [MemberState]                     VARCHAR (50)    NULL,
    [ZipCode]                         VARCHAR (10)    NULL,
    [ContractNumber]                  VARCHAR (50)    NULL,
    [MemberStatus]                    VARCHAR (50)    NULL,
    [SNPIndicator]                    CHAR (1)        NULL,
    [LowIncomeSubsidy]                VARCHAR (5)     NULL,
    [AdherenceType]                   VARCHAR (50)    NULL,
    [AdherenceDrugName]               VARCHAR (100)   NULL,
    [InitialFillDate]                 DATE            NULL,
    [LatestDispensedDate]             DATE            NULL,
    [DaysSupplyCount]                 VARCHAR (5)     NULL,
    [NextFillDate]                    DATE            NULL,
    [PharmacyName]                    VARCHAR (100)   NULL,
    [PharmacyPhoneNumber]             VARCHAR (20)    NULL,
    [PharmacyAddressLine1]            VARCHAR (100)   NULL,
    [PharmacyCity]                    VARCHAR (100)   NULL,
    [PharmacyState]                   VARCHAR (2)     NULL,
    [PharmacyZipCode]                 VARCHAR (15)    NULL,
    [PrescriberId]                    VARCHAR (50)    NULL,
    [PrescriberName]                  VARCHAR (100)   NULL,
    [PriorYearPDC]                    DECIMAL (10, 3) NULL,
    [PDCYTD]                          DECIMAL (10, 3) NULL,
    [MissedDaysYTD]                   VARCHAR (5)     NULL,
    [MissedDaysQ1]                    VARCHAR (5)     NULL,
    [MissedDaysQ2]                    VARCHAR (5)     NULL,
    [MissedDaysQ3]                    VARCHAR (5)     NULL,
    [MissedDaysQ4]                    VARCHAR (5)     NULL,
    [LatetofillIndicator]             CHAR (1)        NULL,
    [Eligiblefor_30_90conversion]     CHAR (1)        NULL,
    [Eligibleforlowercostalternative] CHAR (1)        NULL,
    [FillIndicator]                   VARCHAR (10)    NULL,
    [STARGoal]                        VARCHAR (10)    NULL,
    [DaysSupplyToAdherent]            VARCHAR (5)     NULL,
    [SUPDOpportunity]                 CHAR (1)        NULL,
    [MA_90_DayConv_Denominator]       VARCHAR (5)     NULL,
    [MA_90_DayConv_Numerator]         VARCHAR (5)     NULL,
    [ChronicallyNonAdherent]          VARCHAR (10)    NULL,
    [RowStatus]                       CHAR (1)        DEFAULT ((0)) NULL,
    [SubgroupNumber]                  VARCHAR (20)    NULL,
    [SubgroupName]                    VARCHAR (20)    NULL,
    [CopStgLoadStatus]                TINYINT         DEFAULT ((0)) NULL,
    [LoadDate]                        DATE            NULL,
    PRIMARY KEY CLUSTERED ([AETMAMedAdherencePlansKey] ASC)
);

