CREATE TABLE [adi].[AETMA_ERUTILIZATION] (
    [AETMA_ERUTILIZATIONKey] INT           IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]       VARCHAR (100) NOT NULL,
    [SrcFileName]            VARCHAR (100) NOT NULL,
    [LoadDate]               DATE          NOT NULL,
    [CreatedDate]            DATE          CONSTRAINT [DF_AETMA_ERUTILIZATIONCreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              VARCHAR (50)  CONSTRAINT [DF_AETMA_ERUTILIZATIONCreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]        DATETIME      CONSTRAINT [DF_AETMA_ERUTILIZATION_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]          VARCHAR (50)  CONSTRAINT [DF_AETMA_ERUTILIZATION_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ProviderGroupNumber]    VARCHAR (20)  NULL,
    [ProviderGroupName]      VARCHAR (20)  NULL,
    [SubgroupName]           VARCHAR (20)  NULL,
    [TIN]                    VARCHAR (20)  NULL,
    [TINName]                VARCHAR (50)  NULL,
    [PIN]                    VARCHAR (20)  NULL,
    [ProviderName]           VARCHAR (50)  NULL,
    [GroupIndicator]         VARCHAR (20)  NULL,
    [LocalMarketCode]        VARCHAR (20)  NULL,
    [LocalMarket]            VARCHAR (50)  NULL,
    [Legacy]                 VARCHAR (20)  NULL,
    [BaselineInd]            VARCHAR (20)  NULL,
    [MemberID]               VARCHAR (50)  NULL,
    [Member]                 VARCHAR (50)  NULL,
    [Year_Month]             VARCHAR (20)  NULL,
    [StartDate]              DATE          NULL,
    [EndDate]                DATE          NULL,
    [Year]                   VARCHAR (20)  NULL,
    [Month]                  VARCHAR (20)  NULL,
    [Diagnosis]              VARCHAR (50)  NULL,
    [MedicalCaseID]          VARCHAR (20)  NULL,
    [ServiceProviderID]      VARCHAR (20)  NULL,
    [ServiceProviderName]    VARCHAR (50)  NULL,
    [ERVisit]                VARCHAR (20)  NULL,
    [ObservationIndicator]   VARCHAR (20)  NULL,
    [Data_As_Of]             DATE          NULL,
    PRIMARY KEY CLUSTERED ([AETMA_ERUTILIZATIONKey] ASC)
);

