CREATE TABLE [adi].[AETMAFinancialMemberDetails] (
    [AETMA_Financial_MbrDetailsKey]    INT             IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]                 VARCHAR (100)   NOT NULL,
    [SrcFileName]                      VARCHAR (100)   NOT NULL,
    [LoadDate]                         DATE            NOT NULL,
    [CreatedDate]                      DATE            CONSTRAINT [DF_AETMA_FinancialMbrDetailsCreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                        VARCHAR (50)    CONSTRAINT [DF_AETMA_FinancialMbrDetailsCreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]                  DATETIME        CONSTRAINT [DF_AETMA_FinancialMbrDetails_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                    VARCHAR (50)    CONSTRAINT [DF_AETMA_FinancialMbrDetails_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ReportGroup]                      VARCHAR (50)    NULL,
    [ReportGroupName]                  VARCHAR (50)    NULL,
    [SubgroupNumber]                   VARCHAR (50)    NULL,
    [SubgroupName]                     VARCHAR (50)    NULL,
    [TIN]                              VARCHAR (12)    NULL,
    [TINName]                          VARCHAR (50)    NULL,
    [PVN]                              VARCHAR (50)    NULL,
    [PIN]                              VARCHAR (50)    NULL,
    [ProviderName]                     VARCHAR (50)    NULL,
    [EffectiveMonth]                   VARCHAR (50)    NULL,
    [Legacy]                           VARCHAR (50)    NULL,
    [SRCMemberID]                      VARCHAR (50)    NULL,
    [LastName]                         VARCHAR (50)    NULL,
    [FirstName]                        VARCHAR (50)    NULL,
    [Age]                              VARCHAR (10)    NULL,
    [AgeBand]                          VARCHAR (50)    NULL,
    [Gender]                           VARCHAR (10)    NULL,
    [Product]                          VARCHAR (50)    NULL,
    [CMSContract]                      VARCHAR (50)    NULL,
    [PBPID]                            VARCHAR (50)    NULL,
    [LineBusiness]                     VARCHAR (50)    NULL,
    [RiskScore_Projected]              VARCHAR (50)    NULL,
    [Revenue]                          MONEY           NULL,
    [MedicalRxCost]                    MONEY           NULL,
    [MedicalCostFundPer]               DECIMAL (18, 2) NULL,
    [RevenueNoPartD]                   MONEY           NULL,
    [MedicalRxCostNoPartD]             MONEY           NULL,
    [EffectiveYear]                    VARCHAR (10)    NULL,
    [EffectiveMonthName]               VARCHAR (10)    NULL,
    [EffectiveDate]                    DATE            NULL,
    [TINReportName]                    VARCHAR (50)    NULL,
    [ProviderReportName]               VARCHAR (50)    NULL,
    [MemberMonths]                     VARCHAR (10)    NULL,
    [AsofDate]                         DATE            NULL,
    [Target]                           VARCHAR (50)    NULL,
    [LocalMarketName]                  VARCHAR (50)    NULL,
    [MarketAvgRiskScore_Projected]     VARCHAR (50)    NULL,
    [MarketMedicalRxCost_PMPM]         MONEY           NULL,
    [MarketMedicalCostFund]            DECIMAL (18, 2) NULL,
    [MarketMedical_RxCostNoPartD_PMPM] MONEY           NULL,
    [MarketRevenueNo_PartD_PMPM]       MONEY           NULL,
    [MarketMedicalCostFund_NoPartD]    DECIMAL (18, 2) NULL,
    [MarketRevenue_PMPM]               MONEY           NULL,
    [ProviderFirstName]                VARCHAR (50)    NULL,
    [ProviderMiddleName]               VARCHAR (50)    NULL,
    [ProviderLastName]                 VARCHAR (50)    NULL,
    [NPI]                              VARCHAR (20)    NULL,
    [Chapter]                          VARCHAR (20)    NULL,
    PRIMARY KEY CLUSTERED ([AETMA_Financial_MbrDetailsKey] ASC)
);

