CREATE TABLE [adi].[AETNA_CODES] (
    [CODE]       VARCHAR (50)  NULL,
    [CODE_VALUE] VARCHAR (50)  NULL,
    [CODE_DESC]  VARCHAR (200) NULL,
    [LKUP_CODE]  VARCHAR (50)  NULL,
    [LKUP_VALUE] VARCHAR (50)  NULL,
    [LKUP_DESC]  VARCHAR (100) NULL
);


GO
CREATE NONCLUSTERED INDEX [ndx_adiAetnaCodes]
    ON [adi].[AETNA_CODES]([CODE] ASC);

