CREATE TABLE [adi].[ClaimAetMA] (
    [ClaimAetMAKey]        INT           IDENTITY (1, 1) NOT NULL,
    [OriginalFileName]     VARCHAR (100) NOT NULL,
    [SrcFileName]          VARCHAR (100) NOT NULL,
    [LoadDate]             DATE          NOT NULL,
    [CreatedDate]          DATE          CONSTRAINT [DF_adiClaimAetMA_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]            VARCHAR (50)  CONSTRAINT [DF_adiClaimAetMA_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]      DATETIME      CONSTRAINT [DF_adiClaimAetMA_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]        VARCHAR (50)  CONSTRAINT [DF_adiClaimAetMA_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ps_unique_id]         VARCHAR (50)  NULL,
    [customer_nbr]         VARCHAR (50)  NULL,
    [group_nbr]            VARCHAR (50)  NULL,
    [idn_indicator]        VARCHAR (5)   NULL,
    [subgroup_nbr]         VARCHAR (50)  NULL,
    [account_nbr]          VARCHAR (50)  NULL,
    [file_id]              VARCHAR (50)  NULL,
    [clm_ln_type_cd]       VARCHAR (5)   NULL,
    [non_prfrrd_srv_cd_1]  VARCHAR (5)   NULL,
    [plsp_prod_cd]         VARCHAR (5)   NULL,
    [product_ln_cd]        VARCHAR (5)   NULL,
    [classification_cd]    VARCHAR (5)   NULL,
    [bnft_pkg_id]          VARCHAR (50)  NULL,
    [plan_id]              VARCHAR (50)  NULL,
    [non_prfrrd_srv_cd_2]  VARCHAR (5)   NULL,
    [fund_ctg_cd]          VARCHAR (5)   NULL,
    [src_subscriber_id]    VARCHAR (50)  NULL,
    [emp_last_nm]          VARCHAR (50)  NULL,
    [emp_first_nm]         VARCHAR (50)  NULL,
    [emp_gender]           VARCHAR (10)  NULL,
    [subscriber_brth_dt]   DATE          NULL,
    [subs_zip_cd]          VARCHAR (5)   NULL,
    [subs_st_postal_cd]    VARCHAR (5)   NULL,
    [coverage_type_cd]     VARCHAR (5)   NULL,
    [ssn_nbr]              VARCHAR (20)  NULL,
    [member_id]            VARCHAR (50)  NULL,
    [src_clm_mbr_id]       VARCHAR (50)  NULL,
    [mem_last_nm]          VARCHAR (50)  NULL,
    [mem_first_nm]         VARCHAR (50)  NULL,
    [mem_gender]           VARCHAR (10)  NULL,
    [mbr_rtp_type_cd]      VARCHAR (5)   NULL,
    [birth_dt]             DATE          NULL,
    [src_clm_id]           VARCHAR (50)  NULL,
    [src_claim_line_id_1]  VARCHAR (5)   NULL,
    [prev_clm_seg_id]      VARCHAR (5)   NULL,
    [derived_tcn_nbr]      VARCHAR (50)  NULL,
    [src_claim_line_id_2]  VARCHAR (5)   NULL,
    [claim_line_id]        VARCHAR (5)   NULL,
    [ntwk_srv_area_id]     VARCHAR (50)  NULL,
    [paid_prvdr_nsa_id]    VARCHAR (50)  NULL,
    [srv_capacity_cd]      VARCHAR (50)  NULL,
    [tax_id_format_cd_1]   VARCHAR (5)   NULL,
    [tax_id_nbr_1]         VARCHAR (50)  NULL,
    [print_nm_1]           VARCHAR (50)  NULL,
    [tax_id_format_cd_2]   VARCHAR (5)   NULL,
    [tax_id_nbr_2]         VARCHAR (50)  NULL,
    [srv_prvdr_id]         VARCHAR (50)  NULL,
    [print_nm_2]           VARCHAR (50)  NULL,
    [address_line_1_txt]   VARCHAR (100) NULL,
    [address_line_2_txt]   VARCHAR (100) NULL,
    [city_nm]              VARCHAR (50)  NULL,
    [state_postal_cd]      VARCHAR (10)  NULL,
    [zip_cd]               VARCHAR (10)  NULL,
    [provider_type_cd]     VARCHAR (10)  NULL,
    [specialty_cd]         VARCHAR (10)  NULL,
    [payee_cd]             VARCHAR (5)   NULL,
    [paid_prvdr_par_cd]    VARCHAR (5)   NULL,
    [received_dt]          DATE          NULL,
    [adjn_dt]              DATE          NULL,
    [srv_start_dt]         DATE          NULL,
    [srv_stop_dt]          DATE          NULL,
    [paid_dt_or_adjn_dt]   DATE          NULL,
    [FILLER_11]            VARCHAR (50)  NULL,
    [FILLER_12]            VARCHAR (50)  NULL,
    [FILLER_13]            VARCHAR (50)  NULL,
    [mdc_cd]               VARCHAR (5)   NULL,
    [drg_cd]               VARCHAR (5)   NULL,
    [prcdr_cd]             VARCHAR (5)   NULL,
    [prcdr_modifier_cd_1]  VARCHAR (5)   NULL,
    [prcdr_type_cd]        VARCHAR (5)   NULL,
    [ICD10_Indicator]      VARCHAR (5)   NULL,
    [MED_COST_SUBCTG_CD]   VARCHAR (5)   NULL,
    [prcdr_group_nbr]      VARCHAR (50)  NULL,
    [type_srv_cd]          VARCHAR (5)   NULL,
    [srv_benefit_cd]       VARCHAR (5)   NULL,
    [tooth_1_nbr]          VARCHAR (50)  NULL,
    [plc_srv_cd]           VARCHAR (5)   NULL,
    [dschrg_status_cd]     VARCHAR (5)   NULL,
    [revenue_cd]           VARCHAR (5)   NULL,
    [hcfa_bill_type_cd]    VARCHAR (5)   NULL,
    [unit_cnt]             VARCHAR (5)   NULL,
    [src_unit_cnt]         VARCHAR (5)   NULL,
    [src_billed_amt]       MONEY         NULL,
    [billed_amt]           MONEY         NULL,
    [not_covered_amt_1]    MONEY         NULL,
    [not_covered_amt_2]    MONEY         NULL,
    [not_covered_amt_3]    MONEY         NULL,
    [clm_ln_msg_cd_1]      VARCHAR (5)   NULL,
    [clm_ln_msg_cd_2]      VARCHAR (5)   NULL,
    [clm_ln_msg_cd_3]      VARCHAR (5)   NULL,
    [covered_amt]          MONEY         NULL,
    [allowed_amt]          MONEY         NULL,
    [Dummy]                VARCHAR (10)  NULL,
    [srv_copay_amt]        MONEY         NULL,
    [src_srv_copay_amt]    MONEY         NULL,
    [deductible_amt]       MONEY         NULL,
    [coinsurance_amt]      MONEY         NULL,
    [src_coins_amt]        MONEY         NULL,
    [bnft_payable_amt]     MONEY         NULL,
    [paid_amt]             MONEY         NULL,
    [cob_paid_amt]         MONEY         NULL,
    [ahf_bfd_amt]          MONEY         NULL,
    [ahf_paid_amt]         MONEY         NULL,
    [negot_savings_amt]    MONEY         NULL,
    [r_c_savings_amt]      MONEY         NULL,
    [cob_savings_amt]      MONEY         NULL,
    [src_cob_svngs_amt]    MONEY         NULL,
    [pri_payer_cvg_cd]     VARCHAR (5)   NULL,
    [cob_type_cd]          VARCHAR (5)   NULL,
    [cob_cd]               VARCHAR (5)   NULL,
    [prcdr_cd_ndc]         VARCHAR (50)  NULL,
    [src_clm_mbr_id_2]     VARCHAR (50)  NULL,
    [clm_ln_status_cd]     VARCHAR (5)   NULL,
    [src_member_id]        VARCHAR (50)  NULL,
    [reversal_cd]          VARCHAR (5)   NULL,
    [admit_cnt]            VARCHAR (5)   NULL,
    [admin_savings_amt]    MONEY         NULL,
    [adj_prvdr_dsgnn_cd]   VARCHAR (5)   NULL,
    [aex_plan_dsgntn_cd]   VARCHAR (5)   NULL,
    [benefit_tier_cd]      VARCHAR (5)   NULL,
    [aex_prvdr_spctg_cd]   VARCHAR (5)   NULL,
    [prod_distnctn_cd]     VARCHAR (5)   NULL,
    [billed_eligible_amt]  MONEY         NULL,
    [SPCLTY_CTG_CLS_CD]    VARCHAR (5)   NULL,
    [poa_cd_1]             VARCHAR (5)   NULL,
    [poa_cd_2]             VARCHAR (5)   NULL,
    [poa_cd_3]             VARCHAR (5)   NULL,
    [FILLER_21]            VARCHAR (50)  NULL,
    [FILLER_22]            VARCHAR (50)  NULL,
    [FILLER_23]            VARCHAR (50)  NULL,
    [pricing_mthd_cd]      VARCHAR (5)   NULL,
    [type_class_cd]        VARCHAR (5)   NULL,
    [specialty_ctg_cd]     VARCHAR (5)   NULL,
    [srv_prvdr_npi]        VARCHAR (50)  NULL,
    [ttl_ded_met_ind]      VARCHAR (50)  NULL,
    [ttl_interest_amt]     MONEY         NULL,
    [ttl_surcharge_amt]    MONEY         NULL,
    [SRV_SPCLTY_CTG_CD]    VARCHAR (5)   NULL,
    [HCFA_PLC_SRV_CD]      VARCHAR (5)   NULL,
    [HCFA_ADMIT_SRC_CD]    VARCHAR (5)   NULL,
    [HCFA_ADMIT_TYPE_CD]   VARCHAR (5)   NULL,
    [SRC_ADMIT_DT]         DATE          NULL,
    [SRC_DISCHARGE_DT]     DATE          NULL,
    [prcdr_modifier_cd_2]  VARCHAR (50)  NULL,
    [prcdr_modifier_cd_3]  VARCHAR (50)  NULL,
    [poa_cd_4]             VARCHAR (5)   NULL,
    [poa_cd_5]             VARCHAR (5)   NULL,
    [poa_cd_6]             VARCHAR (5)   NULL,
    [poa_cd_7]             VARCHAR (5)   NULL,
    [poa_cd_8]             VARCHAR (5)   NULL,
    [poa_cd_9]             VARCHAR (5)   NULL,
    [poa_cd_10]            VARCHAR (5)   NULL,
    [pri_icd9_dx_cd]       VARCHAR (5)   NULL,
    [icd9_dx_cd_2]         VARCHAR (5)   NULL,
    [icd9_dx_cd_3]         VARCHAR (5)   NULL,
    [icd9_dx_cd_4]         VARCHAR (5)   NULL,
    [icd9_dx_cd_5]         VARCHAR (5)   NULL,
    [icd9_dx_cd_6]         VARCHAR (5)   NULL,
    [icd9_dx_cd_7]         VARCHAR (5)   NULL,
    [icd9_dx_cd_8]         VARCHAR (5)   NULL,
    [icd9_dx_cd_9]         VARCHAR (5)   NULL,
    [icd9_dx_cd_10]        VARCHAR (5)   NULL,
    [icd9_prcdr_cd_1]      VARCHAR (5)   NULL,
    [icd9_prcdr_cd_2]      VARCHAR (5)   NULL,
    [icd9_prcdr_cd_3]      VARCHAR (5)   NULL,
    [icd9_prcdr_cd_4]      VARCHAR (5)   NULL,
    [icd9_prcdr_cd_5]      VARCHAR (5)   NULL,
    [icd9_prcdr_cd_6]      VARCHAR (5)   NULL,
    [ahf_det_order_cd]     VARCHAR (5)   NULL,
    [ahf_mbr_coins_amt]    MONEY         NULL,
    [ahf_mbr_copay_amt]    MONEY         NULL,
    [ahf_mbr_ded_amt]      MONEY         NULL,
    [hcfa_admit_type_cd_2] VARCHAR (5)   NULL,
    [FILLER_31]            VARCHAR (5)   NULL,
    [ORG_CD]               VARCHAR (100) NULL,
    [EndMark]              CHAR (1)      NULL,
    [DataDate]             DATE          NULL,
    [FileDate]             DATE          NULL,
    PRIMARY KEY CLUSTERED ([ClaimAetMAKey] ASC)
);

