CREATE TABLE [ast].[ProfileClaims_tgDetails] (
    [ClaimAetMAKey]            INT           NOT NULL,
    [LoadDate]                 DATE          NOT NULL,
    [member_id]                VARCHAR (50)  NULL,
    [ClientMemberKey]          VARCHAR (50)  NULL,
    [seq_claim_id]             VARCHAR (50)  NULL,
    [srcClaimLineID1]          INT           NULL,
    [srcClaimLineID2]          INT           NULL,
    [ReferrersToPreviousClaim] VARCHAR (5)   NULL,
    [provider_type_cd]         VARCHAR (10)  NULL,
    [specialty_cd]             VARCHAR (10)  NULL,
    [srv_prvdr_npi]            VARCHAR (50)  NULL,
    [spcltyCtgClsCd]           VARCHAR (200) NOT NULL,
    [srv_start_dt]             DATE          NULL,
    [srv_stop_dt]              DATE          NULL,
    [src_admit_dt]             DATE          NULL,
    [src_discharge_dt]         DATE          NULL,
    [dschrg_status_cd]         VARCHAR (5)   NULL,
    [drg_cd]                   VARCHAR (5)   NULL,
    [prcdr_cd]                 VARCHAR (5)   NULL,
    [med_cost_subctg_cd]       VARCHAR (5)   NULL,
    [prcdr_group_nbr]          VARCHAR (50)  NULL,
    [plc_srv_cd]               VARCHAR (5)   NULL,
    [plcSrvCd]                 VARCHAR (200) NULL,
    [hcfa_bill_type_cd]        VARCHAR (5)   NULL,
    [paid_amt]                 MONEY         NULL,
    [typeClassCd]              VARCHAR (200) NOT NULL,
    [specialtyCtgCd]           VARCHAR (200) NOT NULL,
    [specialtyCtgType]         VARCHAR (100) NULL,
    [hcfa_plc_srv_cd]          VARCHAR (5)   NULL,
    [hcfaadmitsrccd]           VARCHAR (200) NOT NULL,
    [hcfaadmittype]            VARCHAR (200) NOT NULL,
    [revenueCd]                VARCHAR (200) NOT NULL,
    [prcdr_cd_ndc]             VARCHAR (50)  NULL,
    [pri_icd9_dx_cd]           VARCHAR (5)   NULL,
    [HLFlg]                    VARCHAR (1)   NOT NULL,
    [DLFlg]                    VARCHAR (1)   NOT NULL,
    [AFlg]                     VARCHAR (1)   NOT NULL,
    [BFlg]                     VARCHAR (1)   NOT NULL,
    [CFlg]                     VARCHAR (1)   NOT NULL
);

